language: ruby
rvm:
  - 2.0.0
before_install: gem install bundler -v 1.11.2
notifications:
  slack:
    secure: Lk2lpPCixIRLvapR/8FvHAfLhAkjN9Gp7uKvrzZeKzW463/K/GNA+fOYzcMSaaJOvefoADVc6In7WOBZWhN+WW4S4P/EkBjHaQMIz9VX/5rNrm3kLor2fQEYjXHxli68XZKFPdH50eT49L8KUoDcOiYW5tSkPgoO8zGrCyOkTz6u6HWJo7IAmtxgdMVPrxyXr7QZQOGQLvQf3hhIP68gghGjtjZfyam78sA6HUpfebWQ9SqxzJh8W/d3j45D/iTqypP4o76ALyVuGGYKlOp7Q8LXAa++Ys9s0v8D5jV99sqHPTIq5cu5q2f5aV+KIKMb+H1nJbuHsf5r06tO4U2aphINDiNxfazNBfyWjw7x0vp/OTPvFRdN4SIqM5+9vvLHMOgttoRZN3bfL0SR2bdsJhUqvRW+5BUEFxl4KhpNDZT6DydKw1cbbcMsWJuPTOUnHiGcv11KygVnzJiiryBlTSdqrEGUcmwc718NDlOiOzN3vUm8ee4sgYjXsrPd0JTZ5AtovXdurL4KAhsIY6yDMROsymMd+BLFDU0GQ83+NXldSqGpa6QzJkePB6lb6HiiMv0TO8n+yjk/Qu6wS9d7qCSUr1xoUCPz/OYW3jlVGpx601K8qg0pUnpLMV2zvK+ylZEaErff62NYtbvJ8TLxvrXMxjteThTzoRlS22iGb2g=
